version: "3.8"
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - kafka

  mysql-db:
    image: mysql:latest
    ports:
      - "8081:8081"
    volumes:
      - ./1x2Network.sql:/docker-entrypoint-initdb.d/1x2Network.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=1x2Network
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local